services:
  oidc-server:
    image: oidc-server-fix_fix-cicd-v2:latest
    container_name: oidc-server
    ports:
      - "80:80"
    networks:
      - branch_net

  oidc-client:
    image: oidc-client-fix_fix-cicd-v2:latest
    container_name: oidc-client
    depends_on:
      - oidc-server
    networks:
      - branch_net

networks:
  branch_net:
    driver: bridge