services:
  oidc-server:
    image: oidc-server-${BRANCH_SUFFIX}:latest
    container_name: oidc-server
    ports:
      - "80:80"
    networks:
      - branch_net-${BRANCH_SUFFIX}

  oidc-client:
    image: oidc-client-${BRANCH_SUFFIX}:latest
    container_name: oidc-client
    depends_on:
      - oidc-server
    networks:
      - branch_net-${BRANCH_SUFFIX}

networks:
  branch_net-${BRANCH_SUFFIX}:
    external: true